
FROM microsoft/dotnet:2.2-sdk AS build-env

WORKDIR /app
# Copiando arquivos
COPY systore.sln ./
COPY src/FastReport.OpenSource.Export.PdfSimple/*.csproj ./src/FastReport.OpenSource.Export.PdfSimple/
COPY src/Systore.Api/*.csproj ./src/Systore.Api/
COPY src/Systore.Data/*.csproj ./src/Systore.Data/
COPY src/Systore.Domain/*.csproj ./src/Systore.Domain/
COPY src/Systore.Dtos/*.csproj ./src/Systore.Dtos/
COPY src/Systore.FastReport/*.csproj ./src/Systore.FastReport/
COPY src/Systore.Infra/*.csproj ./src/Systore.Infra/
COPY src/Systore.Services/*.csproj ./src/Systore.Services/
COPY src/Systore.Tests/*.csproj ./src/Systore.Tests/
#restaurando pacotes
RUN dotnet restore 
# Build da aplicacao
COPY . .

WORKDIR /app/src/Systore.Api
RUN dotnet build -c Release -o /app/out

WORKDIR /app/src/Systore.Api
RUN dotnet publish -c Release -o /app/out

COPY src/Systore.Api/appsettings.json /app/out

# Build da imagem
FROM microsoft/dotnet:2.2-aspnetcore-runtime
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "Systore.Api.dll"]